# ---------------- Tools & base configuration ----------------
CARGO    := cargo
DOCKER   := docker
MAKE     := make

# Crate / binary / image name.
PROJECT_NAME := haproxy-spoa-ip-reputation-firehol

# Cross-compilation target used for build, check, lint and run.
TARGET := x86_64-unknown-linux-musl
TARGET_FLAG := --target $(TARGET)
RELEASE_BIN := target/$(TARGET)/release/$(PROJECT_NAME)

# Version embedded in container images (build.rs): exact git tag, else short commit hash.
GIT_VERSION ?= $(shell git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)

# ---------------- Rust package paths / layout ----------------
VENDOR_DIR  := vendor
GEOIP2_DIR  := $(VENDOR_DIR)/geoip2-rs
GEOIP2_PATCH := geoip2-rs.patch

# Directories removed by `clean` (downloaded/generated artifacts).
CLEAN_DIRS := firehol-blocklist-ipsets firehol.mmdb $(VENDOR_DIR) target build

# ---------------- Docker options ----------------
IMAGE_NAME := $(PROJECT_NAME)
DOCKER_BUILD_ARGS := --build-arg GIT_VERSION=$(GIT_VERSION)

# Named volume keeping the FireHOL clone and the generated database across runs.
DOCKER_VOLUME := haproxy-spoa-ip-reputation-firehol-data
DOCKER_RUN_PORTS := -p 9000:9000 -p 8405:8405
DOCKER_RUN_ENV := \
	-e LOG_LEVEL=info \
	-e SPOA_LISTEN_ADRESS=0.0.0.0:9000 \
	-e MMDB_PATH=/app/firehol.mmdb \
	-e DROP_BY_CATEGORY=abuse
DOCKER_RUN_OPTS := --rm $(DOCKER_RUN_PORTS) $(DOCKER_RUN_ENV) -v $(DOCKER_VOLUME):/app

# ---------------- Rust benchmark: cargo bench + flamegraph ----------------
# Scripts run under `make`; forwarding $(CARGO)/$(MAKE) lets scripts reuse the config.
BENCH_OUTPUT_DIR ?= $(abspath build/bench)
# Extra Criterion arguments, e.g. 'spoe/concurrent' or '--measurement-time 20'.
BENCH_ARGS ?=
# Benchmark profiled for the flamegraph and its sampling duration in seconds.
BENCH_PROFILE_FILTER ?= spoe/concurrent/32
BENCH_PROFILE_TIME ?= 15
# Criterion HTML report generated by `cargo bench`.
CRITERION_REPORT := $(abspath target/criterion/report/index.html)

# ---------------- Docker HTTP benchmark ----------------
# Duration (seconds), concurrent connections and URL used by the Docker benchmark.
BENCH_DOCKER_DURATION ?= 60
BENCH_DOCKER_CONNECTIONS ?= 300
BENCH_DOCKER_URL ?= http://127.0.0.1:8080

# ---------------- Phony targets ----------------
.PHONY: all build release run test check lint clippy fmt fmt-check doc audit clean help
.PHONY: patch-geoip2-rs bench bench-docker flamegraph
.PHONY: docker-build docker-run docker-compose-build docker-compose-up docker-compose-down docker-compose-logs docker-touch-mmdb
.PHONY: ci

# ---------------- Main entry point ----------------
all: build

# ---------------- Build targets ----------------
build: patch-geoip2-rs
	$(CARGO) build --release $(TARGET_FLAG)

release: build

run: patch-geoip2-rs
	$(CARGO) run --release $(TARGET_FLAG)

check:
	$(CARGO) check $(TARGET_FLAG)

lint: patch-geoip2-rs
	$(CARGO) clippy $(TARGET_FLAG) --all-targets --all-features -- -D warnings

# Auto-fix clippy lints in place (kept explicit and separate from `lint`).
clippy:
	$(CARGO) clippy --fix --allow-dirty

test: patch-geoip2-rs
	$(CARGO) test

fmt:
	$(CARGO) fmt

fmt-check:
	$(CARGO) fmt -- --check

doc:
	$(CARGO) doc --no-deps

audit:
	$(CARGO) audit

clean:
	$(CARGO) clean
	rm -Rf $(CLEAN_DIRS)

# ---------------- Benchmarking targets ----------------
# Docker HTTP benchmark: starts HAProxy + SPOA in docker compose, patches the SPOE config so the
# agent answers the random IP passed in the `ip` URL parameter and the stick-table expiry is
# shortened, runs wrk (BENCH_DOCKER_CONNECTIONS connections for BENCH_DOCKER_DURATION seconds
# against BENCH_DOCKER_URL/?ip=<random>), then restores the original config. Containers are left
# running (no `docker compose down`).
bench-docker:
	BENCH_DOCKER_DURATION="$(BENCH_DOCKER_DURATION)" \
	BENCH_DOCKER_CONNECTIONS="$(BENCH_DOCKER_CONNECTIONS)" \
	BENCH_DOCKER_URL="$(BENCH_DOCKER_URL)" \
	scripts/bench-docker.sh

# Generate a flamegraph from the profiled benchmark workload.
flamegraph: patch-geoip2-rs
	CARGO="$(CARGO)" BENCH_OUTPUT_DIR="$(BENCH_OUTPUT_DIR)" \
	BENCH_PROFILE_FILTER="$(BENCH_PROFILE_FILTER)" BENCH_PROFILE_TIME="$(BENCH_PROFILE_TIME)" \
	scripts/flamegraph.sh

bench: patch-geoip2-rs bench-docker
	$(CARGO) bench --bench spoe -- $(BENCH_ARGS)
	@printf '\nCriterion report: %s\n' "$(CRITERION_REPORT)"
	$(MAKE) flamegraph

# ---------------- Docker targets ----------------
docker-build:
	$(DOCKER) build $(DOCKER_BUILD_ARGS) -t $(IMAGE_NAME) .

docker-run: docker-build
	$(DOCKER) run $(DOCKER_RUN_OPTS) $(IMAGE_NAME)

docker-compose-build:
	GIT_VERSION=$(GIT_VERSION) $(DOCKER) compose build

docker-compose-up: docker-compose-build
	$(DOCKER) compose up

docker-compose-down:
	$(DOCKER) compose down

docker-compose-logs:
	$(DOCKER) compose logs -f --no-log-prefix --timestamps | sort

docker-touch-mmdb:
	$(DOCKER) compose exec spoa touch /app/firehol.mmdb

# ---------------- Vendor / patching ----------------
patch-geoip2-rs:
	@mkdir -p $(VENDOR_DIR)
	@if [ ! -d $(GEOIP2_DIR)/.git ]; then \
		rm -rf $(GEOIP2_DIR); \
		git clone --depth 1 https://github.com/IncSW/geoip2-rs $(GEOIP2_DIR); \
	fi
	@cd $(GEOIP2_DIR) && git apply ../../$(GEOIP2_PATCH) 2>/dev/null || true

# ---------------- CI & help ----------------
ci: fmt-check lint test build

help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Build targets:"
	@echo "  build              Build release binary ($(TARGET))"
	@echo "  release            Alias for build"
	@echo "  run                Run in release mode"
	@echo ""
	@echo "Development targets:"
	@echo "  test               Run tests"
	@echo "  check              Check code without building"
	@echo "  lint               Run clippy with warnings as errors"
	@echo "  clippy             Auto-fix clippy lints in place"
	@echo "  fmt                Format code"
	@echo "  fmt-check          Check code formatting"
	@echo "  doc                Generate documentation"
	@echo "  bench              Run the Criterion SPOE benchmark (cargo bench) and generate a flamegraph"
	@echo "  bench-docker       Run the Docker HTTP benchmark: HAProxy+SPOA in docker compose via wrk (60s, 300 connections)"
	@echo "  flamegraph         Profile the benchmark workload into $(BENCH_OUTPUT_DIR)/flamegraph.svg"
	@echo "  clean              Clean build artifacts"
	@echo ""
	@echo "Docker targets:"
	@echo "  docker-build       Build docker image"
	@echo "  docker-run         Build and run docker container"
	@echo "  docker-compose-build Build docker-compose services"
	@echo "  docker-compose-up  Start docker-compose services (detached)"
	@echo "  docker-compose-down Stop docker-compose services"
	@echo "  docker-compose-logs View docker-compose logs (follow)"
	@echo "  docker-touch-mmdb  Trigger mmdb reload in container"
	@echo ""
	@echo "Other targets:"
	@echo "  ci                 Run CI pipeline (fmt-check, lint, test, build)"
	@echo "  help               Show this help message"
